application:
  name: blue-event
  build_number: 1
  namespace: thm-app
  containers:
    image: nginx:latest
    resources:
      requests:
        memory: 1536Mi
        cpu: 500m
      limits:
        memory: 1536Mi
        cpu: 1000m
    replicas:
      min: 1
      max: 1
    targetCPUUtilizationPercentage: 70
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 0%
  probe:
    startupProbe:
      httpGet:
        path: /
      initialDelaySeconds: 120
    readinessProbe:
      httpGet:
        path: /
      initialDelaySeconds: 30
    livenessProbe:
      httpGet:
        path: /
      initialDelaySeconds: 60
  destinationRule:
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 25
        http:
          http1MaxPendingRequests: 1024
          maxRequestsPerConnection: 100
      isCustomUse: True
      loadBalancer:
        simple: LEAST_CONN
  virtualService:
    http:
      timeout: 60s
  terminationGracePeriodSeconds: 30
  minReadySeconds: 0

service:
  app:
    domain:
      - blue-event.eks-blue.com
    contextPath: /
    port: 80
    targetPort: 9022

secret:
  kms: true
  jasypt: true
  jwt: true

gateway:
  - name: eks-blue-inner-gw
    namespace: eks-blue-gateway
    host: "*.eks-blue.com"
    
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-group
          operator: In
          values:
          - app    
                